services:
  powersync:
    container_name: powersync-unified
    restart: unless-stopped
    image: journeyapps/powersync-service:latest
    volumes:
      - ./powersync.yaml:/app/powersync.yaml
    env_file: ./.env
    ports:
      - 6060:6060
      - 9090:9090 # for telemetry
